name: sj_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 추가된 패키지들
  tosspayments_widget_sdk_flutter: ^2.1.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.2.2
  flutter_widget_from_html: ^0.17.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  screenshot: ^3.0.0      # 화면 캡처용
  share_plus: ^10.1.4     # 공유하기 기능
  path_provider: ^2.1.5   # 임시 파일 저장 경로 확보

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/intro_bg.jpg