name: sj_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ì¶”ê°€ëœ íŒ¨í‚¤ì§€ë“¤
  # tosspayments_widget_sdk_flutter: ^2.1.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.2.2
  flutter_widget_from_html: ^0.17.1
  fl_chart: ^1.1.1
  screenshot: ^3.0.0      # í™”ë©´ ìº¡ì²˜ìš©
  share_plus: ^10.1.4     # ê³µìœ í•˜ê¸° ê¸°ëŠ¥
  path_provider: ^2.1.5   # ìž„ì‹œ íŒŒì¼ ì €ìž¥ ê²½ë¡œ í™•ë³´
  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  js: ^0.7.1  # ì›¹ì—ì„œ JS interop ì‚¬ìš©
  uuid: ^4.5.1  # UUID ìƒì„±ìš©

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/intro_bg.jpg

    # ðŸ‘‡ [ì¶”ê°€] íŒŒì¼ ë§¨ ì•„ëž˜ì— ì´ ë‚´ìš©ì„ ë¶™ì—¬ë„£ìœ¼ì„¸ìš”
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # ì¤€ë¹„í•œ ì´ë¯¸ì§€ ê²½ë¡œ
  min_sdk_android: 21 # ì•ˆë“œë¡œì´ë“œ ìµœì†Œ ë²„ì „
  # ðŸ‘‡ ê°¤ëŸ­ì‹œ ë“± ìµœì‹  í°ì—ì„œ ê½‰ ì°¬ ì•„ì´ì½˜(Adaptive Icon)ì„ ìœ„í•´ í•„ìš”
  adaptive_icon_background: "#FFFFFF" # ë°°ê²½ìƒ‰ (í°ìƒ‰)
  adaptive_icon_foreground: "assets/images/icon.png" # ì•„ì´ì½˜ ì´ë¯¸ì§€